import type { Blueprint } from './types'

// ── Markdown export ──────────────────────────────────────────────────────────

export function toMarkdown(bp: Blueprint): string {
  const lines: string[] = []

  lines.push(`# Blueprint: ${bp.repo.owner}/${bp.repo.name}`)
  lines.push('')
  lines.push(`> ${bp.repo.summary}`)
  lines.push('')
  lines.push(`**Repo:** ${bp.repo.url}  `)
  lines.push(`**Branch:** \`${bp.repo.defaultBranch}\`  `)
  lines.push(`**Commit:** \`${bp.repo.commit.slice(0, 8)}\`  `)
  lines.push(`**Generated:** ${new Date(bp.meta.generatedAt).toUTCString()}  `)
  lines.push(`**Mode:** ${bp.meta.mode}`)
  lines.push('')

  // Inventory
  if (bp.inventory.languages.length || bp.inventory.frameworks.length) {
    lines.push('## Stack')
    lines.push('')
    if (bp.inventory.languages.length) lines.push(`**Languages:** ${bp.inventory.languages.join(', ')}`)
    if (bp.inventory.frameworks.length) lines.push(`**Frameworks:** ${bp.inventory.frameworks.join(', ')}`)
    if (bp.inventory.packageManager) lines.push(`**Package manager:** ${bp.inventory.packageManager}`)
    lines.push('')
  }

  // Zones
  lines.push('## Architecture')
  lines.push('')
  lines.push('```mermaid')
  lines.push(toMermaid(bp))
  lines.push('```')
  lines.push('')

  for (const zone of bp.zones) {
    lines.push(`### ${zone.label}`)
    if (zone.description) lines.push('')
    if (zone.description) lines.push(zone.description)
    lines.push('')
    if (zone.folders.length) lines.push(`**Folders:** \`${zone.folders.join('`  `')}\``)
    lines.push(`**Files:** ${zone.fileCount}`)
    if (zone.importantFiles.length) {
      lines.push('')
      lines.push('**Key files:**')
      for (const f of zone.importantFiles.slice(0, 5)) {
        lines.push(`- \`${f}\``)
      }
    }
    lines.push('')
  }

  // Flows
  if (bp.flows.length > 0) {
    lines.push('## Main Flows')
    lines.push('')
    for (const flow of bp.flows) {
      lines.push(`### ${flow.name}`)
      lines.push('')
      lines.push(flow.steps.map(s => s.label).join(' → '))
      lines.push('')
    }
  }

  // Read first
  if (bp.readFirst.length > 0) {
    lines.push('## Read First')
    lines.push('')
    lines.push('Start here to understand the system:')
    lines.push('')
    bp.readFirst.forEach((f, i) => {
      lines.push(`${i + 1}. \`${f}\``)
    })
    lines.push('')
  }

  // External systems
  if (bp.externalSystems.length > 0) {
    lines.push('## External Systems')
    lines.push('')
    lines.push(bp.externalSystems.map(s => `- ${s}`).join('\n'))
    lines.push('')
  }

  lines.push('---')
  lines.push('*Generated by [Blueprint](https://github.com/YashVishwas/blueprint)*')

  return lines.join('\n')
}

// ── Mermaid export ───────────────────────────────────────────────────────────

export function toMermaid(bp: Blueprint): string {
  const lines: string[] = ['graph TD']

  const zoneNodeId: Record<string, string> = {
    experience: 'EXP',
    entrypoints: 'ENT',
    core_logic: 'CORE',
    data: 'DATA',
    external: 'EXT',
    platform: 'PLAT',
  }

  // Nodes
  for (const zone of bp.zones) {
    const id = zoneNodeId[zone.id]
    const label = `${zone.label}\\n${zone.fileCount} files`
    lines.push(`    ${id}["${label}"]`)
  }

  lines.push('')

  // Edges (canonical flow)
  const hasExperience = (bp.zones.find(z => z.id === 'experience')?.fileCount ?? 0) > 0
  const hasEntrypoints = (bp.zones.find(z => z.id === 'entrypoints')?.fileCount ?? 0) > 0
  const hasCoreLogic = (bp.zones.find(z => z.id === 'core_logic')?.fileCount ?? 0) > 0
  const hasData = (bp.zones.find(z => z.id === 'data')?.fileCount ?? 0) > 0
  const hasExternal = (bp.zones.find(z => z.id === 'external')?.fileCount ?? 0) > 0

  if (hasExperience && hasEntrypoints) lines.push('    EXP -->|calls| ENT')
  else if (hasExperience && hasCoreLogic) lines.push('    EXP -->|calls| CORE')

  if (hasEntrypoints && hasCoreLogic) lines.push('    ENT -->|invokes| CORE')
  else if (hasEntrypoints && hasData) lines.push('    ENT -->|reads/writes| DATA')

  if (hasCoreLogic && hasData) lines.push('    CORE -->|reads/writes| DATA')
  if (hasCoreLogic && hasExternal) lines.push('    CORE -->|calls| EXT')

  // Style
  lines.push('')
  lines.push('    classDef experience fill:#eff6ff,stroke:#2563eb,color:#1e40af')
  lines.push('    classDef entrypoints fill:#f5f3ff,stroke:#7c3aed,color:#5b21b6')
  lines.push('    classDef core_logic fill:#f0fdf4,stroke:#16a34a,color:#15803d')
  lines.push('    classDef data fill:#fefce8,stroke:#ca8a04,color:#a16207')
  lines.push('    classDef external fill:#fff7ed,stroke:#ea580c,color:#c2410c')
  lines.push('    classDef platform fill:#f9fafb,stroke:#4b5563,color:#374151')
  lines.push('')
  lines.push('    class EXP experience')
  lines.push('    class ENT entrypoints')
  lines.push('    class CORE core_logic')
  lines.push('    class DATA data')
  lines.push('    class EXT external')
  lines.push('    class PLAT platform')

  return lines.join('\n')
}
